Import("env_samples")

build_env = env_samples.Clone()
# add glog support
build_env.Prepend(CPPPATH = "#/external/glog/include",
                  LIBPATH = "#/external/glog",
                  LIBS = "glog",
                  LINKFLAGS = "-pthread")
build_env.Program("demo_glog", "demo_glog.cpp")