Import("env_common")

build_env = env_common.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("algorithm_unittest", ["algorithm_unittest.cpp"])
