Import("env_algorithm")

env_algorithm.lib_objects.append(env_algorithm.Object("number_theory.cpp"))
env_algorithm.lib_objects.append(env_algorithm.Object("prime.cpp"))

build_env = env_algorithm.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
				  LIBPATH = "#/external/gtest",
				  LIBS = "gtest",
				  LINKFLAGS = "-pthread")
	
build_env.Program("number_theory_unittest",["number_theory_unittest.cpp"])
build_env.Program("prime_unittest", ["prime_unittest.cpp"])