Import("env_algorithm")

build_env = env_algorithm.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
				  LIBPATH = "#/external/gtest",
				  LIBS = "gtest",
				  LINKFLAGS = "-pthread")
	
build_env.Program("point_unittest",["point_unittest.cpp"])
build_env.Program("polygon_unittest", ["polygon_unittest.cpp"])