Import("env_algorithm")

build_env = env_algorithm.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")
	
build_env.Program("point_unittest",["point_unittest.cpp"])
build_env.Program("polygon_unittest", ["polygon_unittest.cpp"])