Import("env")

env_recsys = env.Clone()
Export("env_recsys")

# add jsoncpp support
env_recsys.Prepend(CPPPATH = "#/external/jsoncpp/include")
env_recsys.Prepend(LIBPATH = "#/external/jsoncpp")
env_recsys.Prepend(LIBS = "json")
# add glog support
env_recsys.Prepend(CPPPATH = "#/external/glog/include")
env_recsys.Prepend(LIBPATH = "#/external/glog")
env_recsys.Prepend(LIBS = "glog")
env_recsys.Prepend(LINKFLAGS = "-pthread")

env_recsys.Prepend(LIBPATH = ["#/recsys"])
env_recsys.Prepend(LIBS=["librecsys.a"])
env_recsys.lib_objects = []

SConscript("base/SConscript")
SConscript("neighbor/SConscript")
SConscript("pop/SConscript")
SConscript("project/SConscript")
SConscript("svd/SConscript")
SConscript("util/SConscript")

env_recsys.StaticLibrary("recsys", env_recsys.lib_objects)
