Import("env")

env_recsys = env.Clone()
Export("env_recsys")

# add jsoncpp support
env_recsys.Prepend(CPPPATH = "#/external/jsoncpp/include",
                   LIBPATH = "#/external/jsoncpp",
                   LIBS = "json")
# add glog support
env_recsys.Prepend(CPPPATH = "#/external/glog/include",
                   LIBPATH = "#/external/glog",
                   LIBS = "glog",
                   LINKFLAGS = "-pthread")

env_recsys.Prepend(LIBPATH = ["#/recsys"])
env_recsys.Prepend(LIBS=["librecsys.a"])
env_recsys.lib_objects = []

SConscript("base/SConscript")
SConscript("evaluate/SConscript")
SConscript("neighbor/SConscript")
SConscript("pop/SConscript")
SConscript("project/SConscript")
SConscript("svd/SConscript")
SConscript("util/SConscript")

env_recsys.StaticLibrary("recsys", env_recsys.lib_objects)
