Import("env_samples")

build_env = env_samples.Clone()
# add gflags support
build_env.Prepend(CPPPATH = "#/external/gflags/include",
                  LIBPATH = "#/external/gflags",
                  LIBS = "gflags",
                  LINKFLAGS = "-pthread")
build_env.Program("demo_gflags", "demo_gflags.cpp")