Import("env_samples")

build_env = env_samples.Clone()
# add gflags support
build_env.Prepend(CPPPATH = "#/external/gflags/include")
build_env.Prepend(LIBPATH = "#/external/gflags")
build_env.Prepend(LIBS = "gflags")
build_env.Prepend(LINKFLAGS = "-pthread")
build_env.Program("demo_gflags", "demo_gflags.cpp")