Import("env_common")

build_env = env_common.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
                  LIBPATH = "#/external/gtest",
                  LIBS = "gtest",
                  LINKFLAGS = "-pthread")
# add glog support
build_env.Prepend(CPPPATH = "#/external/glog/include",
                  LIBPATH = "#/external/glog",
                  LIBS = "glog",
                  LINKFLAGS = "-pthread")

build_env.Program("logging_unittest", ["logging_unittest.cpp"])
build_env.Program("logging_helper_unittest", ["logging_helper_unittest.cpp"])