Import("env_samples")

build_env = env_samples.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
                  LIBPATH = "#/external/gtest",
                  LIBS = "gtest",
                  LINKFLAGS = "-pthread")

build_env.Program("demo_gtest", "demo_gtest.cpp")