Import("env_samples")

build_env = env_samples.Clone()
# add gtest's head files & libs
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("demo_gtest", "demo_gtest.cpp")