Import("env_ml")

build_env = env_ml.Clone()
# add gflags support
build_env.Prepend(CPPPATH = "#/external/gflags/include",
                  LIBPATH = "#/external/gflags",
                  LIBS = "gflags")
# import OpenCV Library
build_env.Prepend(CPPPATH = ["#/external/opencv/include"],
                  LIBPATH = ["#/external/opencv/lib"],
                  LIBS=["opencv_core", "opencv_highgui", "opencv_imgproc"])

build_env.Program("mnist_prepare_longan", 
                 ["mnist_prepare_longan.cpp",
                  "mnist_prepare.cpp"])
