Import("env_common")
env_common.lib_objects.append(env_common.Object("stopwatch.cpp"))

build_env = env_common.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
                  LIBPATH = "#/external/gtest",
                  LIBS = "gtest",
                  LINKFLAGS = "-pthread")

build_env.Program("stopwatch_unittest", ["stopwatch_unittest.cpp"])
