Import("env_common")
env_common.lib_objects.append(env_common.Object("stopwatch.cpp"))

build_env = env_common.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("stopwatch_unittest", ["stopwatch_unittest.cpp"])
