Import("env_algorithm")

build_env = env_algorithm.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("bubble_sort_unittest", ["bubble_sort_unittest.cpp"])
build_env.Program("insertion_sort_unittest", ["insertion_sort_unittest.cpp"])
build_env.Program("merge_sort_unittest", ["merge_sort_unittest.cpp"])
build_env.Program("quick_sort_unittest", ["quick_sort_unittest.cpp"])
build_env.Program("quick_sort_mt_unittest", ["quick_sort_mt_unittest.cpp"])
build_env.Program("counting_sort_unittest", ["counting_sort_unittest.cpp"])
