Import("env_recsys")

env_recsys.lib_objects.append(env_recsys.Object("recsys_test_helper.cpp"));

build_env = env_recsys.Clone()
# add gflags support
build_env.Prepend(CPPPATH = "#/external/gflags/include",
                  LIBPATH = "#/external/gflags",
                  LIBS = "gflags")
build_env.Program("implict_convert_longan", 
                 ["implict_convert_longan.cpp",
                  "implict_convert.cpp"])