Import("env")

env_cv = env.Clone()
Export("env_cv")

env_cv.Prepend(LIBPATH = ["#/cv"])
env_cv.Prepend(LIBS=["cv"])
env_cv.lib_objects = []

# import OpenCV Library
env_cv.Prepend(CPPPATH = ["#/external/opencv/include"])
env_cv.Prepend(LIBPATH = ["#/external/opencv/lib"])
env_cv.Prepend(LIBS=["opencv_core", "opencv_highgui", "opencv_imgproc"])

env_cv.Program("hello_cv", ["hello_cv.cpp"])

env_cv.StaticLibrary("cv", env_cv.lib_objects)
