Import("env_common")
env_common.lib_objects.append(env_common.Object("integer.cpp"))
env_common.lib_objects.append(env_common.Object("double.cpp"))

build_env = env_common.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("integer_unittest", ["integer_unittest.cpp"])
build_env.Program("double_unittest", ["double_unittest.cpp"])
