Import("env_common")
env_common.lib_objects.append(env_common.Object("binary_input_stream.cpp"))
env_common.lib_objects.append(env_common.Object("binary_output_stream.cpp"))
env_common.lib_objects.append(env_common.Object("double.cpp"))
env_common.lib_objects.append(env_common.Object("integer.cpp"))
env_common.lib_objects.append(env_common.Object("text_input_stream.cpp"))
env_common.lib_objects.append(env_common.Object("text_output_stream.cpp"))

build_env = env_common.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
                  LIBPATH = "#/external/gtest",
                  LIBS = "gtest",
                  LINKFLAGS = "-pthread")

build_env.Program("integer_unittest", ["integer_unittest.cpp"])
build_env.Program("double_unittest", ["double_unittest.cpp"])
