Import("env_common")

env_common.lib_objects.append(env_common.Object("file_lister.cpp", 
                CPPPATH = "#/external/boost/include"))
env_common.lib_objects.append(env_common.Object("file_util.cpp"))
env_common.lib_objects.append(env_common.Object("system_info.cpp"))

build_env = env_common.Clone()
# add gtest support
build_env.Append(CPPPATH = "#/external/gtest/include",
                 LIBPATH = "#/external/gtest",
                 LIBS = "gtest",
                 LINKFLAGS = "-pthread")
# add boost library
build_env.Append(CPPPATH = "#/external/boost/include",
                 LIBPATH = "#/external/boost/lib",
                 LIBS = ["boost_system", "boost_filesystem"])

build_env.Program("file_lister_unittest", ["file_lister_unittest.cpp"])
build_env.Program("file_util_unittest", ["file_util_unittest.cpp"])
build_env.Program("system_info_unittest", ["system_info_unittest.cpp"])