Import("env_common")

env_common.lib_objects.append(env_common.Object("file_lister.cpp", 
                CPPPATH = "#/external/boost/include"))

build_env = env_common.Clone()
# add gtest support
build_env.Append(CPPPATH = "#/external/gtest/include")
build_env.Append(LIBPATH = "#/external/gtest")
build_env.Append(LIBS = "gtest")
build_env.Append(LINKFLAGS = "-pthread")
# add boost library
build_env.Append(CPPPATH = "#/external/boost/include")
build_env.Append(LIBPATH = "#/external/boost/lib")
build_env.Append(LIBS = ["boost_system", "boost_filesystem"])

build_env.Program("file_lister_unittest", ["file_lister_unittest.cpp"])
