Import("env_common")

build_env = env_common.Clone()
# add gtest support
build_env.Append(CPPPATH = "#/external/gtest/include",
                 LIBPATH = "#/external/gtest",
                 LIBS = "gtest",
                 LINKFLAGS = "-pthread")

build_env.Program("object_buffer_unittest", ["object_buffer_unittest.cpp"])
build_env.Program("pipelined_scheduler_unittest", ["pipelined_scheduler_unittest.cpp"])