Import("env_common")

build_env = env_common.Clone()
# add gtest support
build_env.Append(CPPPATH = "#/external/gtest/include")
build_env.Append(LIBPATH = "#/external/gtest")
build_env.Append(LIBS = "gtest")
build_env.Append(LINKFLAGS = "-pthread")

build_env.Program("object_buffer_unittest", ["object_buffer_unittest.cpp"])
build_env.Program("pipelined_scheduler_unittest", ["pipelined_scheduler_unittest.cpp"])