Import("env")

env_samples = env.Clone()
Export("env_samples")

SConscript("gflags/SConscript")
SConscript("glog/SConscript")
SConscript("gtest/SConscript")
SConscript("helloworld/SConscript")
SConscript("jsoncpp/SConscript")
SConscript("openmp/SConscript")