Import("env")

env_algorithm = env.Clone()
Export("env_algorithm")

env_algorithm.Prepend(LIBPATH = ["#/algorithm"])
env_algorithm.Prepend(LIBS = ["algorithm"])
env_algorithm.lib_objects = []

SConscript("number_theory/SConscript")
SConscript("sort/SConscript")
SConscript("data_structure/SConscript")

env_algorithm.StaticLibrary("algorithm", env_algorithm.lib_objects)