Import("env_algorithm")

build_env = env_algorithm.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
                  LIBPATH = "#/external/gtest",
                  LIBS = "gtest",
                  LINKFLAGS = "-pthread")

build_env.Program("graph_unittest", ["graph_unittest.cpp"])
build_env.Program("euler_path_unittest", ["euler_path_unittest.cpp"])
build_env.Program("bipartite_max_match_unittest", ["bipartite_max_match_unittest.cpp"])
build_env.Program("weighted_bipartite_max_match_unittest", ["weighted_bipartite_max_match_unittest.cpp"])