Import("env_algorithm")

build_env = env_algorithm.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
				  LIBPATH = "#/external/gtest",
				  LIBS = "gtest",
				  LINKFLAGS = "-pthread")
	
build_env.Program("next_combination_unittest", 
				 ["next_combination_unittest.cpp",
				  "next_combination.cpp"])