Import("env")
env.Append(LIBPATH = ["#/common"])
env.Append(LIBS=["common"])

env_common = env.Clone()
# add jsoncpp support
env_common.Append(CPPPATH = "#/external/jsoncpp/include",
                  LIBPATH = "#/external/jsoncpp",
                  LIBS = "json")
env_common.lib_objects = []

Export("env_common")

SConscript("base/SConscript")
SConscript("config/SConscript")
SConscript("lang/SConscript")
SConscript("logging/SConscript")
SConscript("math/SConscript")
SConscript("memory/SConscript")
SConscript("system/SConscript")
SConscript("threading/SConscript")
SConscript("time/SConscript")
SConscript("util/SConscript")

env_common.StaticLibrary("common", env_common.lib_objects)
