Import("env")
env.Append(LIBPATH = ["#/common"])
env.Append(LIBS=["common"])

env_common = env.Clone()
env_common.lib_objects = []
Export("env_common")

SConscript("math/SConscript")
SConscript("system/SConscript")
SConscript("time/SConscript")
SConscript("util/SConscript")

env_common.StaticLibrary("common", env_common.lib_objects)
