Import("env_samples")

build_env = env_samples.Clone()
# add jsoncpp support
build_env.Prepend(CPPPATH = "#/external/jsoncpp/include",
                  LIBPATH = "#/external/jsoncpp",
                  LIBS = "json",
                  LINKFLAGS = "-pthread")

build_env.Program("demo_json", "demo_json.cpp")