Import("env_samples")

build_env = env_samples.Clone()
# add jsoncpp support
build_env.Prepend(CPPPATH = "#/external/jsoncpp/include")
build_env.Prepend(LIBPATH = "#/external/jsoncpp")
build_env.Prepend(LIBS = "json")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("demo_json", "demo_json.cpp")