Import("env_algorithm")

build_env = env_algorithm.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("queue_unittest", ["queue_unittest.cpp"])
build_env.Program("stack_unittest", ["stack_unittest.cpp"])
build_env.Program("binary_heap_unittest", ["binary_heap_unittest.cpp"])
