Import("env_samples")

build_env = env_samples.Clone()
# add poco support
build_env.Append(CPPPATH = "#/external/poco/include",
                 LIBPATH = "#/external/poco",
                 LIBS = ["PocoNet", "PocoUtil", "PocoXML", "PocoFoundation"],
                 LINKFLAGS = "-pthread")

build_env.Program("poco_event", "poco_event.cpp")
build_env.Program("poco_threading", "poco_threading.cpp")
build_env.Program("poco_httpserver", "poco_httpserver.cpp")
