Import("env_samples")

build_env = env_samples.Clone()
# add openmp support
build_env.Prepend(CCFLAGS = "-fopenmp",
                  LINKFLAGS = "-fopenmp")

build_env.Program("demo_openmp", ["demo_openmp.cpp"])