Import("env_common")
env_common.lib_objects.append(env_common.Object("math.cpp"))
env_common.lib_objects.append(env_common.Object("statistic.cpp"))

build_env = env_common.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("math_unittest", ["math_unittest.cpp"])
build_env.Program("statistic_unittest", ["statistic_unittest.cpp"])