Import("env_recsys")

env_recsys.lib_objects.append(env_recsys.Object("rating_list.cpp"));
env_recsys.lib_objects.append(env_recsys.Object("rating_list_loader.cpp"))
#env_recsys.lib_objects.append(env_recsys.Object("rating_matrix_by_item.cpp"))
#env_recsys.lib_objects.append(env_recsys.Object("rating_matrix_by_user.cpp"))

build_env = env_recsys.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("rating_list_unittest", ["rating_list_unittest.cpp"])
build_env.Program("rating_list_loader_unittest", ["rating_list_loader_unittest.cpp"])
#build_env.Program("rating_matrix_by_item_unittest", ["rating_matrix_by_item_unittest.cpp"])
#build_env.Program("rating_matrix_by_user_unittest", ["rating_matrix_by_user_unittest.cpp"])
