Import("env_recsys")

env_recsys.lib_objects.append(env_recsys.Object("rating_list.cpp"))
env_recsys.lib_objects.append(env_recsys.Object("rating_list_loader.cpp"))
env_recsys.lib_objects.append(env_recsys.Object("rating_trait.cpp"))
env_recsys.lib_objects.append(env_recsys.Object("basic_convert.cpp"))
env_recsys.lib_objects.append(env_recsys.Object("basic_train.cpp"))
env_recsys.lib_objects.append(env_recsys.Object("basic_predict.cpp"))
env_recsys.lib_objects.append(env_recsys.Object("basic_evaluate.cpp"))

build_env = env_recsys.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include")
build_env.Prepend(LIBPATH = "#/external/gtest")
build_env.Prepend(LIBS = "gtest")
build_env.Prepend(LINKFLAGS = "-pthread")

build_env.Program("rating_list_unittest", ["rating_list_unittest.cpp"])
build_env.Program("rating_list_loader_unittest", ["rating_list_loader_unittest.cpp"])
build_env.Program("rating_matrix_as_items_unittest", ["rating_matrix_as_items_unittest.cpp"])
build_env.Program("rating_matrix_as_users_unittest", ["rating_matrix_as_users_unittest.cpp"])
build_env.Program("rating_trait_unittest", ["rating_trait_unittest.cpp"])
build_env.Program("basic_evaluate_unittest", ["basic_evaluate_unittest.cpp"])