Import("env_recsys")

env_recsys.lib_objects.append(env_recsys.Object("evaluate_rating_delegate.cpp"))
env_recsys.lib_objects.append(env_recsys.Object("evaluate_ranking_delegate.cpp"))

build_env = env_recsys.Clone()
# add gtest support
build_env.Prepend(CPPPATH = "#/external/gtest/include",
                  LIBPATH = "#/external/gtest",
                  LIBS = "gtest",
                  LINKFLAGS = "-pthread")
